name: C Build Status
	

	on:
	  push:
	    branches: [ main ]
	  pull_request:
	    branches: [ main ]
	

	

	jobs:
	  build:
	

	    runs-on: ubuntu-latest
	

	    steps:
	    - uses: actions/checkout@p
	    - name: make
	      run: make -C 3_Implementation/ all

